USGDM014 -  admin creation nature
2020-D02-java/missions-groupe-3-back pull request #17
Opened 2020-05-16 09:24 UTC by Jonathan-Tapin

2020-05-17 10:26 UTC, XavierCalloch requested changes
La requête post ne fonctionne pas de mon côté, j'ai du mal à voir d'où vient l'erreur. Les requêtes get fonctionnent (dans le navigateur). Néanmoins, les requêtes get et post me renvoient des erreurs 400 dans Postman

2020-05-17 10:36 UTC, XavierCalloch requested changes
La visualisation des missions est correcte en mode user (en local ou en ligne). Cependant, je n'arrive pas à visualiser les missions en mode admin ou manager

2020-05-17 12:33 UTC, Jonathan-Tapin commented
> 
> 
> La requête post ne fonctionne pas de mon côté, j'ai du mal à voir d'où vient l'erreur. Les requêtes >get fonctionnent (dans le navigateur). Néanmoins, les requêtes get et post me renvoient des >erreurs 400 dans Postman
> 
> 
> La visualisation des missions est correcte en mode user (en local ou en ligne). Cependant, je n'arrive pas à visualiser les missions en mode admin ou manager

Jonathan : 
pour la parti requête dans postman : c'est une 400 ou une 403 ? as-tu fais une requête de login avant de faire des requêtes post ou get ? Car j'ai refait les test sur postman de mon côté, sur la branch USGDM014 en back et tout fonctionne, les Get de Nature de mission, le POST et le PATCH. 

En ce qui concerne l'affichage, tu parles de celui des missions ou bien des natures de missions ? Car sur cette branche l'affichage des natures de mission, accessible uniquement en Admin, n'est pas présent. Pour accéder au formulaire de création tu dois => http://localhost:4200/nature-creation. J'ai fait le test du formulaire sur la branch USGD014 en front et en back et le POST fonctionne. Après la création d'une nouvelle nature j'ai fait une requête GET all des natures de mission, et celle créé depuis le formulaire est bien présente. 

J'ai repéré un pb de gestion de contrôle sur le formulaire, je vais effectuer la correction.

2020-05-17 13:43 UTC, XavierCalloch commented
> > La requête post ne fonctionne pas de mon côté, j'ai du mal à voir d'où vient l'erreur. Les requêtes >get fonctionnent (dans le navigateur). Néanmoins, les requêtes get et post me renvoient des >erreurs 400 dans Postman
> > La visualisation des missions est correcte en mode user (en local ou en ligne). Cependant, je n'arrive pas à visualiser les missions en mode admin ou manager
> 
> Jonathan :
> pour la parti requête dans postman : c'est une 400 ou une 403 ? as-tu fais une requête de login avant de faire des requêtes post ou get ? Car j'ai refait les test sur postman de mon côté, sur la branch USGDM014 en back et tout fonctionne, les Get de Nature de mission, le POST et le PATCH.
> 
> En ce qui concerne l'affichage, tu parles de celui des missions ou bien des natures de missions ? Car sur cette branche l'affichage des natures de mission, accessible uniquement en Admin, n'est pas présent. Pour accéder au formulaire de création tu dois => http://localhost:4200/nature-creation. J'ai fait le test du formulaire sur la branch USGD014 en front et en back et le POST fonctionne. Après la création d'une nouvelle nature j'ai fait une requête GET all des natures de mission, et celle créé depuis le formulaire est bien présente.
> 
> J'ai repéré un pb de gestion de contrôle sur le formulaire, je vais effectuer la correction.

Xavier :
Alors pour la partie requête dans Postman, c'est du 403 Forbidden. Je me suis bien connecté à l'application (en local ou en ligne) avant de faire des requêtes post ou get. Je suis bien dans la branche USGDM014 en back.

Pour l'affichage, c'était de la page visualisation des missions (onglet gestion des missions) dont je parlais. Ok je n'avais pas créé de nouvelle branche USGDM014 dans le front, je relance mon code et je vois ça pour la création de mission.

Ca marche pour la suite.

2020-05-17 14:47 UTC, XavierCalloch approved these changes

2020-05-17 14:48 UTC, XavierCalloch approved these changes

2020-05-19 09:25 UTC, antoinethebault approved these changes

2020-05-19 09:25 UTC, merged